name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - API.md
      - docs/*.rst
  pull_request:
    branches:
      - master
    types:
      - ready_for_review
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - README.md
      - API.md
      - docs/*.rst

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.event_name == 'push' || !github.event.pull_request.draft
    timeout-minutes: 10

    steps:
      - name: Checkout the commit
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run BigChainDB node
        run: |
          echo Building and starting up docker containers
          docker-compose -f ./docker-compose.yml up -d

      - name: Install dependencies
        env:
          HUSKY_SKIP_INSTALL: 'true'
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      # ensure BCDB node is up and running
      - run: sleep 20

      - name: Test
        run: npm run test
